version: 2
jobs:
  build:
    working_directory: ~/nestjs-api-seed
    docker:
      - image: easymetrics/circleci-gcp-node8:latest
    branches:
      only:
        - master
        - develop
        - /.*\/feature.*/
        - /release-.*/
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Unit Tests
          command: npm run test:coverage
      - run:
          name: Code Linting
          command: npm run lint
      # - run:
      #     name: Security Scan
      #     command: npm run security
      - run:
          name: Report Code Coverage
          command: npm run report-codeclimate
      - run:
          name: Dist Build
          command: npm run build:dist
      # - run:
      #     name: Decode Google Cloud Credentials
      #     command: echo ${GOOGLE_AUTH} | base64 -i --decode > ${HOME}/gcp-key.json
      # - run:
      #     name: Activate Service Account
      #     command: |
      #       gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      #       gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      #       gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      #       gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      # - run:
      #     name: Docker Login
      #     command: docker login -u _json_key -p "$(cat ${HOME}/gcp-key.json)" https://gcr.io
      # - run:
      #     name: Write Application Configuration
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         echo -e "$(cat .docker/env/.env.prod)\nMONGO_PASS=${MONGO_PASS_ADM} >> .env;
      #       fi
      #       if [ "${CIRCLE_BRANCH}" == "develop" ]; then
      #         echo -e "$(cat .docker/env/.env.dev)\nMONGO_PASS=${MONGO_PASS_ADM} >> .env;
      #       fi
      # - run:
      #     name: Build Application Container
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         docker build -f Dockerfile -t nestjs-api-seed .
      #       fi
      #       if [ "${CIRCLE_BRANCH}" == "develop" ]; then
      #         docker build -f Dockerfile-dev -t nestjs-api-seed .
      #       fi
      # - run:
      #     name: Tag GCP Application Container
      #     command: docker tag nestjs-api-seed gcr.io/easymetrics-gpc/nestjs-api-seed:${CIRCLE_SHA1}
      # - run:
      #     name: Push To Google Container Registry
      #     command: gcloud docker -- push gcr.io/easymetrics-gpc/nestjs-api-seed:${CIRCLE_SHA1}
      # - deploy:
      #     name: Container Engine Deployment Rolling Update
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         gcloud container clusters get-credentials jobtrak-prod-cluster --zone us-east1-b --project easymetrics-gpc
      #         kubectl set image deployment/nestjs-api-seed --namespace=prod nestjs-api-seed=gcr.io/easymetrics-gpc/nestjs-api-seed:${CIRCLE_SHA1}
      #       fi
      #       if [ "${CIRCLE_BRANCH}" == "develop" ]; then
      #         gcloud container clusters get-credentials jobtrak-dev-cluster --zone us-east1-b --project easymetrics-gpc
      #         kubectl set image deployment/nestjs-api-seed --namespace=dev nestjs-api-seed=gcr.io/easymetrics-gpc/nestjs-api-seed:${CIRCLE_SHA1}
      #       fi
